### ISSUE TITLE
PHPMailer integration

### ISSUE THREAD

**Issue by Saikurin** [Reeko94/scolabs-3IW#15]
# Objectif

Permettre d'envoyer des mails simplement depuis une page
Intégrer un système de notification par mail avec gestion de template

# Exemple de code
``` PHP
// Envoie d'un mail simple
OurMailerSystem::sendMail("to@to.com","from@from.com","From Scolabs","Subject","Contenu");

// Envoie d'un mail avec template
$mailer = new OurMailSystem();
$mailer->setDestinataire("to@to.com");
$mailer->setTemplate("nameOfTemplate");
$mailer->send();
```

# Requis
Les informations de l'utilisateur devraient être récupérer en base de données grâce à l'adresse e-mail du destinataire.
L'objet ainsi que l'adresse email et le nom de l'expéditeur seraient récupérer également à travers le template du mail choisi.

**Comment by RobinTHOREL** [comment]
@Reeko94 I want your attention on this point.

I think PHPMailer is good on local ENV perhaps it's would not be working on production ENV.

Let's grow down this priority issue and check your future hosting and the way to send emails from.

**Comment by RobinTHOREL** [comment]
E.g on Heroku hosting :

They are this module : https://devcenter.heroku.com/articles/sendgrid

And you just should to create a `.env` file and set theses variables to let it work : 

(e.g)
`MAILER_URL : smtp://smtp.sendgrid.net:587?encryption=tls&username=app@heroku.com&password=`
`SENDGRID_PASSWORD : password`
`SENDGRID_USERNAME : app@heroku.com`
