### ISSUE TITLE
End Validator form

### ISSUE THREAD

**Issue by Saikurin** [Reeko94/scolabs-3IW#4]
### Objectif

Finir la validation du formulaire dans la class Validator

## RAF
- Vérifier l'unicité d'un compte
- Vérifier le captcha
- Vérifier le mot de passe // checkPwd() -> Regex ? 
- Vérifier les champs mot de passe confirmé // confirmWith existant? 
- Vérifier les valeurs min et max

**Comment by 12Wass** [comment]
Validator terminé : Au besoin lors d'ajout de nouveaux formulaires, on le changera. Pour l'instant il gère parfaitement l'inscription
